version: '2'

services:
 mysql:
  image: mysql:5.7
  container_name: mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=homestead
    - MYSQL_USER=secret
    - MYSQL_PASSWORD=secret
  ports:
    - "3306:3306"